# postgres:
#   host: localhost
#   port: 5432
#   database: kerc
#   user: postgres
#   password: postgres
#   table_name: act
# mongodb:
#   uri: mongodb://localhost:27017
#   database: kerc
#   collection: act
postgres:
  host: localhost
  port: 5432
  database: kerc
  user: postgres
  password: postgres
  tables:
    - table1
    - table2
  all_tables: true # Set this to true to import all tables

mongodb:
  uri: mongodb://localhost:27017
  database: kerc
